Repository melexis/warnings-plugin, pull requests merged in 2024-11, with the labels that each got.

#151 FIX: Line properties in Code Quality report for PolyspaceChecker shall be integers
  src/mlx/warnings/polyspace_checker.py
  tests/test_in/polyspace_code_quality.json
  tests/test_in/polyspace_code_quality_exclude.json
Labels: bug

#157 Fix URL to GitLab's Code Quality report format
  README.rst
Labels: documentation

#150 Support environment variables in the configuration for CoverityChecker
  src/mlx/warnings/regex_checker.py
  src/mlx/warnings/warnings.py
  tests/test_coverity.py
  tests/test_in/code_quality_format.json
  tests/test_in/config_example_coverity.yml
  tests/test_in/config_example_polyspace_error.yml
  tests/test_in/coverity_cq.json
  tests/test_integration.py
  tests/test_polyspace.py
Labels: enhancement

#160 Rename the codeql analysis actions file, because GitHub GUI tells you so
  .github/workflows/codeql-analysis.yml
Labels: automation

#163 Add Code of Conduct
  CONTRIBUTING.md
Labels: documentation
